"""Collect M0 results into results/M0_REPORT_TABLES.md (run with .venv-enh: needs jiwer + pyannote)."""
import json, sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).parent
sys.path.insert(0, str(ROOT))
from asr_bench import CHAR_LANGS, LANGS, score  # noqa: E402

CONDS = ["clean", "noisy", "dfn3", "dfn3a12", "mf2"]
SHORT = {"yue_hant_hk": "yue", "cmn_hans_cn": "cmn", "en_us": "en", "ms_my": "ms", "id_id": "id",
         "ta_in": "ta", "th_th": "th", "vi_vn": "vi"}
QWEN_NAMES = {"yue_hant_hk": "Cantonese", "cmn_hans_cn": "Chinese", "en_us": "English", "ms_my": "Malay",
              "id_id": "Indonesian", "ta_in": "Tamil", "th_th": "Thai", "vi_vn": "Vietnamese"}
WHISPER_NAMES = {"yue_hant_hk": "cantonese", "cmn_hans_cn": "chinese", "en_us": "english", "ms_my": "malay",
                 "id_id": "indonesian", "ta_in": "tamil", "th_th": "thai", "vi_vn": "vietnamese"}


def main():
    lines = ["# M0 results (generated by spike/report.py)", "",
             "FLEURS test, 60 utterances per language, no language hint. CER for yue/cmn/th, WER for the rest.",
             "noisy = babble + pink noise at 5 dB SNR; dfn3/dfn3a12/mf2 = noisy after that enhancer.", ""]
    res = {}
    for f in sorted((ROOT / "results").glob("asr_*.jsonl")):
        rows = [json.loads(l) for l in open(f)]
        if rows:
            res[f.stem[4:]] = rows
    for cond in CONDS:
        have = {m: score([r for r in rows if r["cond"] == cond]) for m, rows in res.items()}
        have = {m: s for m, s in have.items() if s}
        if not have:
            continue
        lines += [f"## {cond}", "", "| model | " + " | ".join(SHORT[l] for l in LANGS) + " | avg (excl. ta) | x realtime |",
                  "|---|" + "---|" * (len(LANGS) + 2)]
        for m, s in have.items():
            vals = [s.get((l, cond)) for l in LANGS]
            ok = [v for l, v in zip(LANGS, vals) if v is not None and l != "ta_in"]
            rt = [1 / r["rtf"] for r in res[m] if r["cond"] == cond and r["rtf"] > 0]
            lines.append(f"| {m} | " + " | ".join(f"{v*100:.1f}" if v is not None else "–" for v in vals)
                         + f" | {sum(ok)/len(ok)*100:.1f} | {sorted(rt)[len(rt)//2]:.0f} |" if ok else "")
        lines.append("")
    lines += ["## Language ID accuracy (clean)", "", "| model | " + " | ".join(SHORT[l] for l in LANGS) + " |",
              "|---|" + "---|" * len(LANGS)]
    for m, rows in res.items():
        acc = []
        for l in LANGS:
            rs = [r for r in rows if r["lang"] == l and r["cond"] == "clean"]
            names = QWEN_NAMES if m.startswith(("qwen", "confucius")) else WHISPER_NAMES
            hit = sum(1 for r in rs if names[l].lower() in (r["lid"] or "").lower())
            acc.append(f"{hit/len(rs)*100:.0f}" if rs else "–")
        lines.append(f"| {m} | " + " | ".join(acc) + " |")
    out = ROOT / "results" / "M0_REPORT_TABLES.md"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
